name: CI/CD Deployment

on:
  push:
    branches:
      - main  # or master, whichever branch you deploy from

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Check out the latest code
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. (Optional) Run tests
      - name: Run tests
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install -r requirements.txt
          python manage.py test

      # 3. Deploy to EC2 via SSH
      # - name: Deploy to EC2
      #   uses: appleboy/ssh-action@v0.1.8
      #   with:
      #     host: ${{ secrets.EC2_HOST }}
      #     username: ${{ secrets.EC2_USER }}   # e.g., "ubuntu"
      #     key: ${{ secrets.EC2_SSH_KEY }}       # Your private SSH key (add as a secret)
      #     port: 22
      #     script: |
      #       cd /home/ubuntu/aws-ec2-ci-cd
      #       git pull origin main
      #       source venv/bin/activate
      #       pip install -r requirements.txt
      #       python manage.py migrate --noinput
      #       python manage.py collectstatic --noinput
      #       sudo systemctl restart gunicorn
